server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /view/
      suffix: .jsp
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pxp6118.uta.cloud:3306/pxp6118_sdp?useSSL=false
    username: pxp6118_team3
    password: SDPteam3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    generate-ddl: false
